# Generated by Django 4.2.13 on 2025-06-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weightlifting', '0002_alter_program_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='competition',
            field=models.BooleanField(default=False),
        ),
    ]
